language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hudsondye/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true hudsondye/react-test npm test

after_success:
  - docker build -t hudsondye/multi-client ./client
  - docker build -t hudsondye/multi-nginx ./nginx
  - docker build -t hudsondye/multi-server ./server
  - docker build -t hudsondye/multi-worker ./worker
